Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_basic?characterEncoding=utf8
    username: big
    password: tlawjddn1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: ${job.name:NONE}
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging.level.org.springframework.batch: DEBUG
